/**
 * generated by Xtext 2.10.0
 */
package xtext.workshop.advanced.formatting.table;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cell</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.workshop.advanced.formatting.table.Cell#getText <em>Text</em>}</li>
 * </ul>
 *
 * @see xtext.workshop.advanced.formatting.table.TablePackage#getCell()
 * @model
 * @generated
 */
public interface Cell extends EObject
{
  /**
   * Returns the value of the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Text</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text</em>' attribute.
   * @see #setText(String)
   * @see xtext.workshop.advanced.formatting.table.TablePackage#getCell_Text()
   * @model
   * @generated
   */
  String getText();

  /**
   * Sets the value of the '{@link xtext.workshop.advanced.formatting.table.Cell#getText <em>Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Text</em>' attribute.
   * @see #getText()
   * @generated
   */
  void setText(String value);

} // Cell
