/**
 * generated by Xtext 2.10.0
 */
package xtext.workshop.advanced.formatting.table;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Document</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.workshop.advanced.formatting.table.Document#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see xtext.workshop.advanced.formatting.table.TablePackage#getDocument()
 * @model
 * @generated
 */
public interface Document extends EObject
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link xtext.workshop.advanced.formatting.table.Table}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Elements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see xtext.workshop.advanced.formatting.table.TablePackage#getDocument_Elements()
   * @model containment="true"
   * @generated
   */
  EList<Table> getElements();

} // Document
