/**
 * generated by Xtext 2.10.0
 */
package xtext.workshop.advanced.formatting.table;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Header Cell</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xtext.workshop.advanced.formatting.table.TablePackage#getHeaderCell()
 * @model
 * @generated
 */
public interface HeaderCell extends Cell
{
} // HeaderCell
