/**
 * generated by Xtext 2.10.0
 */
package xtext.workshop.advanced.formatting.table;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see xtext.workshop.advanced.formatting.table.TableFactory
 * @model kind="package"
 * @generated
 */
public interface TablePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "table";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.workshop.xtext/advanced/formatting/Table";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "table";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TablePackage eINSTANCE = xtext.workshop.advanced.formatting.table.impl.TablePackageImpl.init();

  /**
   * The meta object id for the '{@link xtext.workshop.advanced.formatting.table.impl.DocumentImpl <em>Document</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.workshop.advanced.formatting.table.impl.DocumentImpl
   * @see xtext.workshop.advanced.formatting.table.impl.TablePackageImpl#getDocument()
   * @generated
   */
  int DOCUMENT = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOCUMENT__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Document</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOCUMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link xtext.workshop.advanced.formatting.table.impl.TableImpl <em>Table</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.workshop.advanced.formatting.table.impl.TableImpl
   * @see xtext.workshop.advanced.formatting.table.impl.TablePackageImpl#getTable()
   * @generated
   */
  int TABLE = 1;

  /**
   * The feature id for the '<em><b>Caption</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE__CAPTION = 0;

  /**
   * The feature id for the '<em><b>Rows</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE__ROWS = 1;

  /**
   * The number of structural features of the '<em>Table</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link xtext.workshop.advanced.formatting.table.impl.CaptionImpl <em>Caption</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.workshop.advanced.formatting.table.impl.CaptionImpl
   * @see xtext.workshop.advanced.formatting.table.impl.TablePackageImpl#getCaption()
   * @generated
   */
  int CAPTION = 2;

  /**
   * The feature id for the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAPTION__LABEL = 0;

  /**
   * The number of structural features of the '<em>Caption</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAPTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link xtext.workshop.advanced.formatting.table.impl.RowImpl <em>Row</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.workshop.advanced.formatting.table.impl.RowImpl
   * @see xtext.workshop.advanced.formatting.table.impl.TablePackageImpl#getRow()
   * @generated
   */
  int ROW = 3;

  /**
   * The feature id for the '<em><b>Cells</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW__CELLS = 0;

  /**
   * The number of structural features of the '<em>Row</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link xtext.workshop.advanced.formatting.table.impl.CellImpl <em>Cell</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.workshop.advanced.formatting.table.impl.CellImpl
   * @see xtext.workshop.advanced.formatting.table.impl.TablePackageImpl#getCell()
   * @generated
   */
  int CELL = 4;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL__TEXT = 0;

  /**
   * The number of structural features of the '<em>Cell</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link xtext.workshop.advanced.formatting.table.impl.HeaderCellImpl <em>Header Cell</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.workshop.advanced.formatting.table.impl.HeaderCellImpl
   * @see xtext.workshop.advanced.formatting.table.impl.TablePackageImpl#getHeaderCell()
   * @generated
   */
  int HEADER_CELL = 5;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEADER_CELL__TEXT = CELL__TEXT;

  /**
   * The number of structural features of the '<em>Header Cell</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEADER_CELL_FEATURE_COUNT = CELL_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link xtext.workshop.advanced.formatting.table.impl.DataCellImpl <em>Data Cell</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.workshop.advanced.formatting.table.impl.DataCellImpl
   * @see xtext.workshop.advanced.formatting.table.impl.TablePackageImpl#getDataCell()
   * @generated
   */
  int DATA_CELL = 6;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_CELL__TEXT = CELL__TEXT;

  /**
   * The number of structural features of the '<em>Data Cell</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_CELL_FEATURE_COUNT = CELL_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link xtext.workshop.advanced.formatting.table.Document <em>Document</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Document</em>'.
   * @see xtext.workshop.advanced.formatting.table.Document
   * @generated
   */
  EClass getDocument();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.workshop.advanced.formatting.table.Document#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see xtext.workshop.advanced.formatting.table.Document#getElements()
   * @see #getDocument()
   * @generated
   */
  EReference getDocument_Elements();

  /**
   * Returns the meta object for class '{@link xtext.workshop.advanced.formatting.table.Table <em>Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Table</em>'.
   * @see xtext.workshop.advanced.formatting.table.Table
   * @generated
   */
  EClass getTable();

  /**
   * Returns the meta object for the containment reference '{@link xtext.workshop.advanced.formatting.table.Table#getCaption <em>Caption</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Caption</em>'.
   * @see xtext.workshop.advanced.formatting.table.Table#getCaption()
   * @see #getTable()
   * @generated
   */
  EReference getTable_Caption();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.workshop.advanced.formatting.table.Table#getRows <em>Rows</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rows</em>'.
   * @see xtext.workshop.advanced.formatting.table.Table#getRows()
   * @see #getTable()
   * @generated
   */
  EReference getTable_Rows();

  /**
   * Returns the meta object for class '{@link xtext.workshop.advanced.formatting.table.Caption <em>Caption</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Caption</em>'.
   * @see xtext.workshop.advanced.formatting.table.Caption
   * @generated
   */
  EClass getCaption();

  /**
   * Returns the meta object for the attribute '{@link xtext.workshop.advanced.formatting.table.Caption#getLabel <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Label</em>'.
   * @see xtext.workshop.advanced.formatting.table.Caption#getLabel()
   * @see #getCaption()
   * @generated
   */
  EAttribute getCaption_Label();

  /**
   * Returns the meta object for class '{@link xtext.workshop.advanced.formatting.table.Row <em>Row</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Row</em>'.
   * @see xtext.workshop.advanced.formatting.table.Row
   * @generated
   */
  EClass getRow();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.workshop.advanced.formatting.table.Row#getCells <em>Cells</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Cells</em>'.
   * @see xtext.workshop.advanced.formatting.table.Row#getCells()
   * @see #getRow()
   * @generated
   */
  EReference getRow_Cells();

  /**
   * Returns the meta object for class '{@link xtext.workshop.advanced.formatting.table.Cell <em>Cell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cell</em>'.
   * @see xtext.workshop.advanced.formatting.table.Cell
   * @generated
   */
  EClass getCell();

  /**
   * Returns the meta object for the attribute '{@link xtext.workshop.advanced.formatting.table.Cell#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see xtext.workshop.advanced.formatting.table.Cell#getText()
   * @see #getCell()
   * @generated
   */
  EAttribute getCell_Text();

  /**
   * Returns the meta object for class '{@link xtext.workshop.advanced.formatting.table.HeaderCell <em>Header Cell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Header Cell</em>'.
   * @see xtext.workshop.advanced.formatting.table.HeaderCell
   * @generated
   */
  EClass getHeaderCell();

  /**
   * Returns the meta object for class '{@link xtext.workshop.advanced.formatting.table.DataCell <em>Data Cell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Data Cell</em>'.
   * @see xtext.workshop.advanced.formatting.table.DataCell
   * @generated
   */
  EClass getDataCell();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  TableFactory getTableFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link xtext.workshop.advanced.formatting.table.impl.DocumentImpl <em>Document</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.workshop.advanced.formatting.table.impl.DocumentImpl
     * @see xtext.workshop.advanced.formatting.table.impl.TablePackageImpl#getDocument()
     * @generated
     */
    EClass DOCUMENT = eINSTANCE.getDocument();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOCUMENT__ELEMENTS = eINSTANCE.getDocument_Elements();

    /**
     * The meta object literal for the '{@link xtext.workshop.advanced.formatting.table.impl.TableImpl <em>Table</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.workshop.advanced.formatting.table.impl.TableImpl
     * @see xtext.workshop.advanced.formatting.table.impl.TablePackageImpl#getTable()
     * @generated
     */
    EClass TABLE = eINSTANCE.getTable();

    /**
     * The meta object literal for the '<em><b>Caption</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TABLE__CAPTION = eINSTANCE.getTable_Caption();

    /**
     * The meta object literal for the '<em><b>Rows</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TABLE__ROWS = eINSTANCE.getTable_Rows();

    /**
     * The meta object literal for the '{@link xtext.workshop.advanced.formatting.table.impl.CaptionImpl <em>Caption</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.workshop.advanced.formatting.table.impl.CaptionImpl
     * @see xtext.workshop.advanced.formatting.table.impl.TablePackageImpl#getCaption()
     * @generated
     */
    EClass CAPTION = eINSTANCE.getCaption();

    /**
     * The meta object literal for the '<em><b>Label</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CAPTION__LABEL = eINSTANCE.getCaption_Label();

    /**
     * The meta object literal for the '{@link xtext.workshop.advanced.formatting.table.impl.RowImpl <em>Row</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.workshop.advanced.formatting.table.impl.RowImpl
     * @see xtext.workshop.advanced.formatting.table.impl.TablePackageImpl#getRow()
     * @generated
     */
    EClass ROW = eINSTANCE.getRow();

    /**
     * The meta object literal for the '<em><b>Cells</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROW__CELLS = eINSTANCE.getRow_Cells();

    /**
     * The meta object literal for the '{@link xtext.workshop.advanced.formatting.table.impl.CellImpl <em>Cell</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.workshop.advanced.formatting.table.impl.CellImpl
     * @see xtext.workshop.advanced.formatting.table.impl.TablePackageImpl#getCell()
     * @generated
     */
    EClass CELL = eINSTANCE.getCell();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CELL__TEXT = eINSTANCE.getCell_Text();

    /**
     * The meta object literal for the '{@link xtext.workshop.advanced.formatting.table.impl.HeaderCellImpl <em>Header Cell</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.workshop.advanced.formatting.table.impl.HeaderCellImpl
     * @see xtext.workshop.advanced.formatting.table.impl.TablePackageImpl#getHeaderCell()
     * @generated
     */
    EClass HEADER_CELL = eINSTANCE.getHeaderCell();

    /**
     * The meta object literal for the '{@link xtext.workshop.advanced.formatting.table.impl.DataCellImpl <em>Data Cell</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.workshop.advanced.formatting.table.impl.DataCellImpl
     * @see xtext.workshop.advanced.formatting.table.impl.TablePackageImpl#getDataCell()
     * @generated
     */
    EClass DATA_CELL = eINSTANCE.getDataCell();

  }

} //TablePackage
