/**
 * generated by Xtext 2.10.0
 */
package xtext.workshop.advanced.formatting.table;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Table</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.workshop.advanced.formatting.table.Table#getCaption <em>Caption</em>}</li>
 *   <li>{@link xtext.workshop.advanced.formatting.table.Table#getRows <em>Rows</em>}</li>
 * </ul>
 *
 * @see xtext.workshop.advanced.formatting.table.TablePackage#getTable()
 * @model
 * @generated
 */
public interface Table extends EObject
{
  /**
   * Returns the value of the '<em><b>Caption</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Caption</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Caption</em>' containment reference.
   * @see #setCaption(Caption)
   * @see xtext.workshop.advanced.formatting.table.TablePackage#getTable_Caption()
   * @model containment="true"
   * @generated
   */
  Caption getCaption();

  /**
   * Sets the value of the '{@link xtext.workshop.advanced.formatting.table.Table#getCaption <em>Caption</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Caption</em>' containment reference.
   * @see #getCaption()
   * @generated
   */
  void setCaption(Caption value);

  /**
   * Returns the value of the '<em><b>Rows</b></em>' containment reference list.
   * The list contents are of type {@link xtext.workshop.advanced.formatting.table.Row}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rows</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rows</em>' containment reference list.
   * @see xtext.workshop.advanced.formatting.table.TablePackage#getTable_Rows()
   * @model containment="true"
   * @generated
   */
  EList<Row> getRows();

} // Table
