/*
 * generated by Xtext 2.10.0
 */
package xtext.workshop.advanced.formatting.tests

import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.eclipse.xtext.resource.SaveOptions
import org.eclipse.xtext.serializer.ISerializer
import org.junit.Test
import org.junit.runner.RunWith
import xtext.workshop.advanced.formatting.table.Document

import static org.junit.Assert.*

@RunWith(XtextRunner)
@InjectWith(TableInjectorProvider)
class FormattingTest{

	@Inject extension ParseHelper<Document> 
	@Inject extension ISerializer

	val expectedResult='''
	{|
	|-|Orange|Apple    |more
	|-|Bread |Pie      |more
	|-!Butter!Ice cream|and more
	|}
	
	{|
	|-|Orange|10 |7.00
	|-|Bread |4  |3.00
	|-|Butter|1  |5.00
	|-!Total |100|15.00
	|}
	'''
	val testInput='''
		{||-|Orange|Apple|more|-|Bread|Pie|more|-!Butter!Ice cream|and more|}
		
		{||-|Orange|10|7.00|-|Bread |4 |3.00|-|Butter|1 |5.00|-!Total |100|15.00|}
	'''
	@Test 
	def void testFormatter() {
		assertEquals(expectedResult,
			testInput.parse.serialize(SaveOptions.newBuilder.format().getOptions()))
	}

}
