/*
 * generated by Xtext 2.10.1
 */
package org.xtext.example


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class KeywordsStandaloneSetup extends KeywordsStandaloneSetupGenerated {

	def static void doSetup() {
		new KeywordsStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
