/*
 * generated by Xtext 2.25.0-SNAPSHOT
 */
package org.example.domainmodel.ide;

import org.eclipse.xtext.ide.editor.contentassist.IdeContentProposalProvider;
import org.eclipse.xtext.ide.editor.quickfix.IQuickFixProvider;
import org.eclipse.xtext.ide.server.codeActions.ICodeActionService2;
import org.eclipse.xtext.ide.server.codeActions.QuickFixCodeActionService;
import org.eclipse.xtext.ide.server.codelens.ICodeLensService;
import org.eclipse.xtext.ide.server.hover.HoverService;
import org.example.domainmodel.ide.codelens.DomainmodelCodeLensService;
import org.example.domainmodel.ide.contentassist.DomainmodelIdeContentProposalProvider;
import org.example.domainmodel.ide.hover.EclipseLikeHoverService;
import org.example.domainmodel.ide.quickfix.DomainmodelQuickfixProvider;

/**
 * Use this class to register ide components.
 */
public class DomainmodelIdeModule extends AbstractDomainmodelIdeModule {

	public Class<? extends IdeContentProposalProvider> bindIdeContentProposalProvider() {
		return DomainmodelIdeContentProposalProvider.class;
	}

	public Class<? extends ICodeActionService2> bindICodeActionService2() {
		return QuickFixCodeActionService.class;
	}

	public Class<? extends IQuickFixProvider> bindIQuickFixProvider() {
		return DomainmodelQuickfixProvider.class;
	}

	public Class<? extends ICodeLensService> bindICodeLensService() {
		return DomainmodelCodeLensService.class;
	}

	public Class<? extends HoverService> bindHoverService() {
		return EclipseLikeHoverService.class;
	}
}
