/*
 * generated by Xtext 2.10.0
 */
package xtext.workshop.advanced.formatting.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTableScopeProvider extends DelegatingScopeProvider {
}
