/*
 * generated by Xtext 2.10.0
 */
package xtext.workshop.advanced.formatting


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TableStandaloneSetup extends TableStandaloneSetupGenerated {

	def static void doSetup() {
		new TableStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
