/*
 * generated by Xtext 2.10.0
 */
package xtext.workshop.advanced.formatting


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class TableRuntimeModule extends AbstractTableRuntimeModule {
}
