/**
 * generated by Xtext 2.10.0
 */
package xtext.workshop.advanced.formatting.ui.contentassist;

import xtext.workshop.advanced.formatting.ui.contentassist.AbstractTableProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class TableProposalProvider extends AbstractTableProposalProvider {
}
