/**
 * generated by Xtext 2.10.0
 */
package xtext.workshop.advanced.formatting.table.impl;

import org.eclipse.emf.ecore.EClass;

import xtext.workshop.advanced.formatting.table.HeaderCell;
import xtext.workshop.advanced.formatting.table.TablePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Header Cell</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class HeaderCellImpl extends CellImpl implements HeaderCell
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected HeaderCellImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TablePackage.Literals.HEADER_CELL;
  }

} //HeaderCellImpl
