/*
 * generated by Xtext 2.10.0
 */
package xtext.workshop.advanced.formatting.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import xtext.workshop.advanced.formatting.table.ui.internal.TableActivator;

public class TableUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TableActivator.getInstance().getInjector("xtext.workshop.advanced.formatting.Table");
	}

}
