/**
 * generated by Xtext 2.10.0
 */
package xtext.workshop.advanced.formatting.tests;

import com.google.inject.Inject;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipse.xtext.junit4.XtextRunner;
import org.eclipse.xtext.junit4.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import xtext.workshop.advanced.formatting.table.Document;
import xtext.workshop.advanced.formatting.tests.TableInjectorProvider;

@RunWith(XtextRunner.class)
@InjectWith(TableInjectorProvider.class)
@SuppressWarnings("all")
public class TableParsingTest {
  @Inject
  private ParseHelper<Document> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Hello Xtext!");
      _builder.newLine();
      final Document result = this.parseHelper.parse(_builder);
      Assert.assertNotNull(result);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
