/**
 * generated by Xtext 2.10.0
 */
package xtext.workshop.advanced.formatting.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import xtext.workshop.advanced.formatting.ui.AbstractTableUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class TableUiModule extends AbstractTableUiModule {
  public TableUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
