/**
 * generated by Xtext 2.10.0
 */
package xtext.workshop.advanced.formatting.validation;

import xtext.workshop.advanced.formatting.validation.AbstractTableValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class TableValidator extends AbstractTableValidator {
}
