/**
 * generated by Xtext 2.10.0
 */
package xtext.workshop.advanced.formatting;

import xtext.workshop.advanced.formatting.TableStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class TableStandaloneSetup extends TableStandaloneSetupGenerated {
  public static void doSetup() {
    TableStandaloneSetup _tableStandaloneSetup = new TableStandaloneSetup();
    _tableStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
