/**
 * generated by Xtext 2.10.0
 */
package xtext.workshop.advanced.formatting;

import xtext.workshop.advanced.formatting.AbstractTableRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class TableRuntimeModule extends AbstractTableRuntimeModule {
}
