/*
 * generated by Xtext 2.10.0
 */
package xtext.workshop.advanced.formatting.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import xtext.workshop.advanced.formatting.parser.antlr.internal.InternalTableParser;
import xtext.workshop.advanced.formatting.services.TableGrammarAccess;

public class TableParser extends AbstractAntlrParser {

	@Inject
	private TableGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTableParser createParser(XtextTokenStream stream) {
		return new InternalTableParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Document";
	}

	public TableGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TableGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
