/*
 * generated by Xtext 2.10.0
 */
package xtext.workshop.advanced.formatting.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TableAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("xtext/workshop/advanced/formatting/parser/antlr/internal/InternalTable.tokens");
	}
}
