/*
 * generated by Xtext 2.25.0-SNAPSHOT
 */
package org.example.domainmodel;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class DomainmodelStandaloneSetup extends DomainmodelStandaloneSetupGenerated {

	public static void doSetup() {
		new DomainmodelStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
