/*
 * generated by Xtext 2.10.0
 */
package xtext.workshop.advanced.formatting.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import xtext.workshop.advanced.formatting.table.ui.internal.TableActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TableExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TableActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TableActivator.getInstance().getInjector(TableActivator.XTEXT_WORKSHOP_ADVANCED_FORMATTING_TABLE);
	}
	
}
